package com.example.samira.neurobooster.controller;

import android.content.Context;

import com.example.samira.neurobooster.model.Question;

/**
 * Created by Samira on 5/28/16.
 */
public class questioninput {
    questionDAO questiondao;
    public questioninput(Context context) {
         questiondao = new questionDAO(context);
    }

    public void addAllQuestion() {
        String cat;

        cat ="Maths";
        Question q1 = new Question(1,"5+2 = ?", "1", "8", "6", "7","2",cat);
        questiondao.addQuestion(q1);
        Question q2 = new Question(2,"2+18 = ?", "1", "19", "20", "18","2",cat);
        questiondao.addQuestion(q2);
        Question q3 = new Question(3,"10-3 = ?", "1", "7", "8", "5","6",cat);
        questiondao.addQuestion(q3);
        Question q4 = new Question(4,"5+7 = ?", "1", "13", "14", "12","6",cat);
        questiondao.addQuestion(q4);
        Question q5 = new Question(5,"3-1 = ?", "1", "3", "1", "2","6",cat);
        questiondao.addQuestion(q5);
        Question q6 = new Question(6,"0+1 = ?", "1", "0", "10", "1","6",cat);
        questiondao.addQuestion(q6);
//        Question q7 = new Question("9-9 = ?", "0", "9", "1", "0");
//        this.addQuestion(q7);
//        Question q8 = new Question("3+6 = ?", "8", "7", "9", "9");
//        this.addQuestion(q8);
//        Question q9 = new Question("1+5 = ?", "6", "7", "5", "6");
//        this.addQuestion(q9);
//        Question q10 = new Question("7-5 = ?", "3", "2", "6", "2");
//        this.addQuestion(q10);
//        Question q11 = new Question("7-2 = ?", "7", "6", "5", "5");
//        this.addQuestion(q11);
//        Question q12 = new Question("3+5 = ?", "8", "7", "5", "8");
//        this.addQuestion(q12);
//        Question q13 = new Question("0+6 = ?", "7", "6", "5", "6");
//        this.addQuestion(q13);
//        Question q14 = new Question("12-10 = ?", "1", "2", "3", "2");
//        this.addQuestion(q14);
//        Question q15 = new Question("12+2 = ?", "14", "15", "16", "14");
//        this.addQuestion(q15);
//        Question q16 = new Question("2-1 = ?", "2", "1", "0", "1");
//        this.addQuestion(q16);
//        Question q17 = new Question("6-6 = ?", "6", "12", "0", "0");
//        this.addQuestion(q17);
//        Question q18 = new Question("5-1 = ?", "4", "3", "2", "4");
//        this.addQuestion(q18);
//        Question q19 = new Question("4+2 = ?", "6", "7", "5", "6");
//        this.addQuestion(q19);
//        Question q20 = new Question("5+1 = ?", "6", "7", "5", "6");
//        this.addQuestion(q20);
//        Question q21 = new Question("5-4 = ?", "5", "4", "1", "1");
//        this.addQuestion(q21);
// END
    }
public void addAllQuestion2() {
    String cat;
    Question q0;

    cat ="Maths";
    Question q1 = new Question(1,"Look at this series: 8, 6, 9, 23, 87 , ... What number should come next?", "4", "128", "226", "324","429",cat);
    questiondao.addQuestion(q1);
    Question q2 = new Question(2,"Look at this series: 7, 10, 8, 11, 9, 12, ... What number should come next?", "2", "10", "7", "13","12",cat);
    questiondao.addQuestion(q2);
    Question q3 = new Question(3,"Look at this series: 80, 10, 70, 15, 60, ... What number should come next?", "1", "20", "30", "25","50",cat);
    questiondao.addQuestion(q3);
    Question q4 = new Question(4,"Father is aged three times more than his son Ronit. After 8 years, he would be two and a half times of Ronit's age. After further 8 years, how many times would he be of Ronit's age?", "1", "2 times", "5/2 times", "11/2 times","3 times",cat);
    questiondao.addQuestion(q4);
    Question q5 = new Question(5,"The sum of ages of 5 children born at the intervals of 3 years each is 50 years. What is the age of the youngest child?", "2", "10 years", "4 years", "8 years","None of the above",cat);
    questiondao.addQuestion(q5);
    Question q6 = new Question(6,"The age of father 10 years ago was thrice the age of his son. Ten years hence, father's age will be twice that of his son. The ratio of their present ages is:", "2", "5 : 2", "7 : 3", "9 : 2","13 : 4",cat);
    questiondao.addQuestion(q6);
    Question q7 = new Question(7,"A train running at the speed of 60 km/hr crosses a pole in 9 seconds. What is the length of the train?", "4", "120 metres", "130 metres", "180 metres","150 metres",cat);
    questiondao.addQuestion(q7);
    Question q8 = new Question(8,"A train passes a station platform in 36 seconds and a man standing on the platform in 20 seconds. If the speed of the train is 54 km/hr, what is the length of the platform?", "2", "120 m", "240 m", "300 m","None of the above",cat);
    questiondao.addQuestion(q8);
    Question q9 = new Question(9,"The length of the bridge, which a train 130 metres long and travelling at 45 km/hr can cross in 30 seconds, is:", "3", "200 m", "245 m", "524 m","254 m",cat);
    questiondao.addQuestion(q9);
    Question q10 = new Question(10,"A, B and C can do a piece of work in 20, 30 and 60 days respectively. In how many days can A do the work if he is assisted by B and C on every third day?", "3", "16 days", "12 days", "15 days","18 days",cat);
    questiondao.addQuestion(q10);
    Question q11 = new Question(11,"A is thrice as good as workman as B and therefore is able to finish a job in 60 days less than B. Working together, they can do it in:", "2", "25 days", "22.5 days", "30 days","26 days",cat);
    questiondao.addQuestion(q11);
    Question q12 = new Question(12,"A and B can do a work in 8 days, B and C can do the same work in 12 days. A, B and C together can finish it in 6 days. A and C together will do it in :", "2", "4 days", "8 days", "6 days","10 days",cat);
    questiondao.addQuestion(q12);
    Question q13 = new Question(13,"A and B together can do a piece of work in 30 days. A having worked for 16 days, B finishes the remaining work alone in 44 days. In how many days shall B finish the whole work alone?", "1", "60 days", "40 days", "70 days","50 days",cat);
    questiondao.addQuestion(q13);
    Question q14 = new Question(14,"If selling price is doubled, the profit triples. Find the profit percent.", "1", "100", "120", "180","200",cat);
    questiondao.addQuestion(q14);
    Question q15 = new Question(15,"In a certain store, the profit is 320% of the cost. If the cost increases by 25% but the selling price remains constant, approximately what percentage of the selling price is the profit?", "1", "70%", "80%", "50%","60%",cat);
    questiondao.addQuestion(q15);
    Question q16 = new Question(16,"A vendor bought toffees at 6 for a rupee. How many for a rupee must he sell to gain 20%?", "3", "6", "7", "5","3",cat);
    questiondao.addQuestion(q16);
    Question q17 = new Question(17,"In how many ways can the letters of the word 'LEADER' be arranged?", "2", "320", "360", "245","None of the above",cat);
    questiondao.addQuestion(q17);
    Question q18 = new Question(18,"Out of 7 consonants and 4 vowels, how many words of 3 consonants and 2 vowels can be formed?", "2", "1050", "25200", "14723","None of the above",cat);
    questiondao.addQuestion(q18);
    Question q19 = new Question(19,"From a group of 7 men and 6 women, five persons are to be selected to form a committee so that at least 3 men are there on the committee. In how many ways can it be done?", "4", "657", "675", "745","756",cat);
    questiondao.addQuestion(q19);
    Question q20 = new Question(20,"Tea worth Rs. 126 per kg and Rs. 135 per kg are mixed with a third variety in the ratio 1 : 1 : 2. If the mixture is worth Rs. 153 per kg, the price of the third variety per kg will be:", "1", "Rs. 175.50", "Rs. 115.50", "Rs. 115.25","Rs. 157.25",cat);
    questiondao.addQuestion(q20);
    Question q21 = new Question(21,"A milk vendor has 2 cans of milk. The first contains 25% water and the rest milk. The second contains 50% water. How much milk should he mix from each of the containers so as to get 12 litres of milk such that the ratio of water to milk is 3 : 5?", "4", "6 litres, 8 litres", "8 litres, 6 litres", "7 litres, 6 litres","6 litres, 6 litres",cat);
    questiondao.addQuestion(q21);
    Question q22 = new Question(22,"By investing in 16% stock at 64, one earns Rs. 1500. The investment made is:", "1", "Rs. 5760", "Rs. 5670", "Rs. 7650","Rs. 7560",cat);
    questiondao.addQuestion(q22);
    Question q23 = new Question(23,"A man buys Rs. 20 shares paying 9% dividend. The man wants to have an interest of 12% on his money. The market value of each share is:", "1", "Rs. 15", "Rs. 16", "Rs. 18","Rs. 14",cat);
    questiondao.addQuestion(q23);
    Question q24 = new Question(24,"In order to obtain an income of Rs. 650 from 10% stock at Rs. 96, one must make an investment of:", "3", "Rs. 6420", "Rs. 6250", "Rs. 6240","Rs. 6402",cat);
    questiondao.addQuestion(q24);
    Question q25 = new Question(25,"A train can travel 50% faster than a car. Both start from point A at the same time and reach point B 75 kms away from A at the same time. On the way, however, the train lost about 12.5 minutes while stopping at the stations. The speed of the car is:", "3", "140 kmph", "180 kmph", "120 kmph","150 kmph",cat);
    questiondao.addQuestion(q25);
    Question q26 = new Question(26,"Excluding stoppages, the speed of a bus is 54 kmph and including stoppages, it is 45 kmph. For how many minutes does the bus stop per hour?", "1", "10", "20", "18","25",cat);
    questiondao.addQuestion(q26);
    Question q27 = new Question(27,"A farmer travelled a distance of 61 km in 9 hours. He travelled partly on foot @ 4 km/hr and partly on bicycle @ 9 km/hr. The distance travelled on foot is:", "4", "17 km", "18 km", "12 km","16 km",cat);
    questiondao.addQuestion(q27);
    Question q28 = new Question(28,"In covering a distance of 30 km, Abhay takes 2 hours more than Sameer. If Abhay doubles his speed, then he would take 1 hour less than Sameer. Abhay's speed is:", "1", "5 kmph", "4.5 kmph", "5.5 kmph","7.5 kmph",cat);
    questiondao.addQuestion(q28);
    Question q29 = new Question(29,"Today is Monday. After 61 days, it will be:", "3", "Monday", "Sunday", "Saturday","Tuesday",cat);
    questiondao.addQuestion(q29);
    Question q30 = new Question(30,"The calendar for the year 2007 will be the same for the year:", "1", "2018", "2017", "2016","2014",cat);
    questiondao.addQuestion(q30);
    Question q31 = new Question(31,"Which of the following is not a leap year?", "3", "800", "600", "700","2000",cat);
    questiondao.addQuestion(q31);
    Question q32 = new Question(32,"January 1, 2007 was Monday. What day of the week lies on Jan. 1, 2008?", "1", "Tuesday", "Friday", "Monday","Sunday",cat);
    questiondao.addQuestion(q32);
    Question q33 = new Question(33,"The ratio between the length and the breadth of a rectangular park is 3 : 2. If a man cycling along the boundary of the park at the speed of 12 km/hr completes one round in 8 minutes, then the area of the park (in sq. m) is:", "1", "153600", "307200", "30720","37200",cat);
    questiondao.addQuestion(q33);
    Question q34 = new Question(34,"The ratio between the perimeter and the breadth of a rectangle is 5 : 1. If the area of the rectangle is 216 sq. cm, what is the length of the rectangle?", "3", "12 cm", "Data inadequate", "18 cm","None of the above",cat);
    questiondao.addQuestion(q34);
    Question q35 = new Question(35,"The percentage increase in the area of a rectangle, if each of its sides is increased by 20% is:", "4", "43%", "40%", "54%","44%",cat);
    questiondao.addQuestion(q35);
    Question q36 = new Question(36,"A rectangular park 60 m long and 40 m wide has two concrete crossroads running in the middle of the park and rest of the park has been used as a lawn. If the area of the lawn is 2109 sq. m, then what is the width of the road?", "2", "5 m", "3 m", "4 m","None of the above",cat);
    questiondao.addQuestion(q36);
    Question q37 = new Question(37,"What least number must be added to 1056, so that the sum is completely divisible by 23 ?", "1", "2", "16", "17","12",cat);
    questiondao.addQuestion(q37);
    Question q38 = new Question(38,"1397 x 1397 = ?", "3", "1951509", "2051609", "1951609","3126509",cat);
    questiondao.addQuestion(q38);
    Question q39 = new Question(39,"The largest 4 digit number exactly divisible by 88 is:", "1", "9944", "4499", "8877","7788",cat);
    questiondao.addQuestion(q39);
    Question q40 = new Question(40,"Which of the following is a prime number ?", "4", "81", "33", "93","97",cat);
    questiondao.addQuestion(q40);
    Question q41 = new Question(41,"8988 ÷ 8 ÷ 4 = ?", "4", "332.875", "164.875", "285.875","280.875",cat);
    questiondao.addQuestion(q41);
    Question q42 = new Question(42,"Which one of the following can't be the square of natural number ?", "1", "143642", "75625", "30976","None of the above",cat);
    questiondao.addQuestion(q42);
    Question q43 = new Question(43,"3251 + 587 + 369 - ? = 3007", "4", "1260", "1300", "1400","1200",cat);
    questiondao.addQuestion(q43);
    Question q44 = new Question(44,"106 x 106 - 94 x 94 = ?", "1", "2400", "2480", "1800","2580",cat);
    questiondao.addQuestion(q44);
    Question q45 = new Question(45,"Three unbiased coins are tossed. What is the probability of getting at most two heads?", "3", "7/2", "8/7", "7/8","2/7",cat);
    questiondao.addQuestion(q45);
    Question q46 = new Question(46,"What is the probability of getting a sum 9 from two throws of a dice?", "1", "1/9", "1/4", "1/7","1/6",cat);
    questiondao.addQuestion(q46);
    Question q47 = new Question(47,"Tickets numbered 1 to 20 are mixed up and then a ticket is drawn at random. What is the probability that the ticket drawn has a number which is a multiple of 3 or 5?", "4", "3/40", "1/21", "2/17","9/20",cat);
    questiondao.addQuestion(q47);
    Question q48 = new Question(48,"If one-third of one-fourth of a number is 15, then three-tenth of that number is:", "1", "54", "45", "48","51",cat);
    questiondao.addQuestion(q48);
    Question q49 = new Question(49,"Three times the first of three consecutive odd integers is 3 more than twice the third. The third integer is:", "2", "10", "15", "1","16",cat);
    questiondao.addQuestion(q49);
    Question q50 = new Question(50,"A two-digit number is such that the product of the digits is 8. When 18 is added to the number, then the digits are reversed. The number is:", "3", "20", "10", "24","26",cat);
    questiondao.addQuestion(q50);
    Question q51 = new Question(51,"The sum of the digits of a two-digit number is 15 and the difference between the digits is 3. What is the two-digit number?", "48", "88", "68", "78","Cannot be determined",cat);
    questiondao.addQuestion(q51);
    Question q52 = new Question(52,"The sum of the squares of three numbers is 138, while the sum of their products taken two at a time is 131. Their sum is:", "2", "19", "20", "22","None of the above",cat);
    questiondao.addQuestion(q52);
    Question q53 = new Question(53,"Find a positive number which when increased by 17 is equal to 60 times the reciprocal of the number.", "3", "17", "18", "3","6",cat);
    questiondao.addQuestion(q53);
    Question q54 = new Question(54,"The sum of even numbers between 1 and 31 is:", "4", "130", "104", "142","240",cat);
    questiondao.addQuestion(q54);
    Question q55 = new Question(55,"On multiplying a number by 7, the product is a number each of whose digits is 3. The smallest such number is:", "1", "47619", "49719", "47219","42419",cat);
    questiondao.addQuestion(q55);
    Question q56 = new Question(56,"The difference of the squares of two consecutive odd integers is divisible by which of the following integers ?", "1", "8", "10", "1","6",cat);
    questiondao.addQuestion(q56);
    Question q57 = new Question(57,"Two pipes A and B can fill a cistern in 37.5 minutes and 45 minutes respectively. Both pipes are opened. The cistern will be filled in just half an hour, if the B is turned off after:", "3", "7 min", "8 min", "9 min","4 min",cat);
    questiondao.addQuestion(q57);
    Question q58 = new Question(58,"A tank is filled in 5 hours by three pipes A, B and C. The pipe C is twice as fast as B and B is twice as fast as A. How much time will pipe A alone take to fill the tank?", "1", "35 hours", "64 hours", "42 hours","26 hours",cat);
    questiondao.addQuestion(q58);
    Question q59 = new Question(59,"Two pipes A and B can fill a tank in 20 and 30 minutes respectively. If both the pipes are used together, then how long will it take to fill the tank?", "1", "12 min", "16 min", "14 min","11 min",cat);
    questiondao.addQuestion(q59);
    Question q60 = new Question(60,"A number was divided successively in order by 4, 5 and 6. The remainders were respectively 2, 3 and 4. The number is:", "3", "320", "104", "214","426",cat);
    questiondao.addQuestion(q60);


    cat ="Science";
    q0 = new Question(1,"Brass gets discoloured in air because of the presence of which of the following gases in air?", "2", "Oxygen", "Hydrogen sulphide", "Carbon dioxide","Nitrogen",cat);
    questiondao.addQuestion(q0);
    q0 = new Question(1,"Which of the following is a non metal that remains liquid at room temperature?", "2", "Phosphorous", "Bromine", "Chlorine","Helium",cat);
    questiondao.addQuestion(q0);
    q0 = new Question(1,"Chlorophyll is a naturally occurring chelate compound in which central metal is", "2", "calcium", "magnesium", "iron","copper",cat);
    questiondao.addQuestion(q0);
    q0 = new Question(1,"Which of the following is used in pencils?", "1", "Graphite", "Silicon", "Charcoal","Phosphorous",cat);
    questiondao.addQuestion(q0);
    q0 = new Question(1,"Which of the following metals forms an amalgam with other metals?", "2", "Tin", "Mercury", "Lead","Zinc",cat);
    questiondao.addQuestion(q0);
    q0 = new Question(1,"The gas usually filled in the electric bulb is", "1", "Nitrogen", "Hydrogen", "Carbon Dioxide","Oxygen",cat);
    questiondao.addQuestion(q0);
    q0 = new Question(1,"Washing soda is the common name for", "1", "Sodium carbonate", "Calcium carbonate", "Sodium bicarbonate","Calcium bicarbonate",cat);
    questiondao.addQuestion(q0);
    q0 = new Question(1,"Quartz crystals normally used in quartz clocks etc. is chemically", "3", "germanium oxide", "sodium silicate", "silicon dioxide","a mixture of germanium oxide and silicon dioxide",cat);
    questiondao.addQuestion(q0);
    q0 = new Question(1,"Which of the gas is not known as green house gas?", "4", "Nitrogen", "Carbon Dioxide", "Oxygen","Hydrogen",cat);
    questiondao.addQuestion(q0);
    q0 = new Question(1,"Bromine is a", "2", "black solid", "red liqiud", "highly inflammable gas","colourless liquid",cat);
    questiondao.addQuestion(q0);
    q0 = new Question(1,"The hardest substance available on earth is", "4", "Platinum", "Gold", "Iron","Diamond",cat);
    questiondao.addQuestion(q0);
    q0 = new Question(1,"The variety of coal in which the deposit contains recognisable traces of the original plant material is", "1", "peat", "bitumen", "lignite","anthracite",cat);
    questiondao.addQuestion(q0);
    q0 = new Question(1,"Tetraethyl lead is used as", "4", "pain killer", "fire extinguisher", "mosquito repellent","petrol additive",cat);
    questiondao.addQuestion(q0);
    q0 = new Question(1,"Which of the following is used as a lubricant?", "1", "Graphite", "Silica", "Iron Oxide","Diamond",cat);
    questiondao.addQuestion(q0);
    q0 = new Question(1,"The inert gas which is substituted for nitrogen in the air used by deep sea divers for breathing, is", "3", "Krypton", "Xenon", "Helium","Argon",cat);
    questiondao.addQuestion(q0);
    q0 = new Question(1,"The gases used in different types of welding would include", "4", "oxygen and hydrogen", "oxygen, hydrogen, acetylene and nitrogen", "oxygen, acetylene and argon","oxygen and acetylene",cat);
    questiondao.addQuestion(q0);
    q0 = new Question(1,"The property of a substance to absorb moisture from the air on exposure is called", "2", "osmosis", "deliquescence", "desiccation","efflorescence",cat);
    questiondao.addQuestion(q0);
    q0 = new Question(1,"In which of the following activities silicon carbide is used?", "3", "Making cement and glass", "Disinfecting water of ponds", "cutting very hard substances","Making casts for statues",cat);
    questiondao.addQuestion(q0);
    q0 = new Question(1,"The average salinity of sea water is", "2", "3%", "3.5%", "2.5%","2%",cat);
    questiondao.addQuestion(q0);
    q0 = new Question(1,"When an iron nail gets rusted, iron oxide is formed", "3", "without any change in the weight of the nail", "with decrease in the weight of the nail", "with increase in the weight of the nail","without any change in colour or weight of the nail",cat);
    questiondao.addQuestion(q0);
    q0 = new Question(1,"Galvanised iron sheets have a coating of", "4", "chromium", "lead", "tin","zinc",cat);
    questiondao.addQuestion(q0);
    q0 = new Question(1,"Among the various allotropes of carbon,", "3", "coke is the hardest, graphite is the softest", "diamond is the hardest, coke is the softest", "diamond is the hardest, graphite is the softest","diamond is the hardest, lamp black is the softest",cat);
    questiondao.addQuestion(q0);
    q0 = new Question(1,"The group of metals Fe, Co, Ni may best called as", "1", "transition metals", "main group metals", "alkali metals","rare metals",cat);
    questiondao.addQuestion(q0);
    q0 = new Question(1,"Heavy water is", "1", "deuterium oxide", "PH7", "rain water","tritium oxide",cat);
    questiondao.addQuestion(q0);
    q0 = new Question(1,"The chemical (ethyl mercaptan) added to the otherwise odourless LPG cooking gas for imparting a detectable smell to the gas is a compound of", "1", "bromine", "chlorine", "fluorine","sulphur",cat);
    questiondao.addQuestion(q0);
    q0 = new Question(1,"The element common to all acids is", "1", "hydrogen", "sulphur", "carbon","oxygen",cat);
    questiondao.addQuestion(q0);
    q0 = new Question(1,"Non stick cooking utensils are coated with", "1", "Teflon", "PVC", "black paint","polystyrene",cat);
    questiondao.addQuestion(q0);
    q0 = new Question(1,"Monazite is an ore of", "4", "titanium", "zirconium", "iron","thorium",cat);
    questiondao.addQuestion(q0);
    q0 = new Question(1,"Carbon, diamond and graphite are together called", "1", "allotropes", "isomorphs", "isomers","isotopes",cat);
    questiondao.addQuestion(q0);
    q0 = new Question(1,"Potassium nitrate is used in", "2", "medicine", "fertiliser", "salt","glass",cat);
    questiondao.addQuestion(q0);
    q0 = new Question(1,"Permanent hardness of water may be removed by the addition of", "1", "sodium carbonate", "alum", "potassium permanganate","lime",cat);
    questiondao.addQuestion(q0);
    q0 = new Question(1,"Soda water contains", "3", "carbonic acid", "sulphuric acid", "carbon dioxide","nitrous acid",cat);
    questiondao.addQuestion(q0);
    q0 = new Question(1,"The most important ore of aluminium is", "4", "galena", "calamine", "calcite","bauxite",cat);
    questiondao.addQuestion(q0);
    q0 = new Question(1,"Most soluble in water is", "4", "camphor", "sulphur", "common salt","sugar",cat);
    questiondao.addQuestion(q0);
    q0 = new Question(1,"Which of the following was to be discovered first in the chromospheres of the sun?", "4", "Krypton", "Xenon", "Neon","Helium",cat);
    questiondao.addQuestion(q0);
    q0 = new Question(1,"Which of the following is in liquid form at room temperature?", "3", "Lithium", "Sodium", "Francium","Cerium",cat);
    questiondao.addQuestion(q0);
    q0 = new Question(1,"Sodium metal is kept under", "4", "petrol", "water", "alcohol","kerosene",cat);
    questiondao.addQuestion(q0);
    q0 = new Question(1,"Which of the following are the ingredients of gun metal?", "4", "Iron, Zinc, Titanium", "Iron, tin", "Iron, Brass, Tin","Copper, Tin",cat);
    questiondao.addQuestion(q0);
    q0 = new Question(1,"From which mineral is radium obtained?", "4", "Rutile", "Haematite", "Limestone","Pitchblende",cat);
    questiondao.addQuestion(q0);
    q0 = new Question(1,"What is laughing gas?", "1", "Nitrous Oxide", "Carbon monoxide", "Sulphur dioxide","Hydrogen peroxide",cat);
    questiondao.addQuestion(q0);
    q0 = new Question(1,"Actinides are the elements with atomic numbers from", "3", "97 to 104", "101 to 115", "89 to 103","36 from 43",cat);
    questiondao.addQuestion(q0);
    q0 = new Question(1,"The two elements that are frequently used for making transistors are", "2", "boron and aluminium", "silicon and germanium", "iridium and tungsten","niobium and columbium",cat);
    questiondao.addQuestion(q0);
    q0 = new Question(1,"The filament of an electric bulb is made of", "1", "tungsten", "nichrome", "iron","graphite",cat);
    questiondao.addQuestion(q0);
    q0 = new Question(1,"Diamond is an allotropic form of", "2", "germanium", "carbon", "silicon","sulphur",cat);
    questiondao.addQuestion(q0);
    q0 = new Question(1,"In fireworks, the green flame is produced because of", "2", "sodium", "barium", "mercury","potassium",cat);
    questiondao.addQuestion(q0);
    q0 = new Question(1,"Permanent hardness of water can be removed by adding", "2", "chlorine", "washing soda", "potassium permanganate","bleaching powder",cat);
    questiondao.addQuestion(q0);
    q0 = new Question(1,"Marsh gas is", "3", "nitrogen", "ethane", "methane","hydrogen",cat);
    questiondao.addQuestion(q0);
    q0 = new Question(1,"LPG consists of mainly", "4", "methane, ethane and hexane", "ethane, hexane and nonane", "methane, hexane and nonane","methane, butane and propane",cat);
    questiondao.addQuestion(q0);
    q0 = new Question(1,"Air is a/an", "4", "compound", "element", "electrolyte","mixture",cat);
    questiondao.addQuestion(q0);
    q0 = new Question(1,"Production of chlorofluorocarbons (CFC) gas which is proposed to be banned in India, is used in which of the following domestic products?","2","Television", "Refrigerator", "Tube light", "Cooking gas",cat);
    questiondao.addQuestion(q0);
    q0 = new Question(1,"Balloons are filled with", "2", "nitrogen", "helium", "oxygen","argon",cat);
    questiondao.addQuestion(q0);
    q0 = new Question(1,"Which of the following does not contain a coinage metal?", "2", "Silver and Gold", "Zinc and Gold", "Copper and Silver","Copper and Gold",cat);
    questiondao.addQuestion(q0);
    q0 = new Question(1,"Which metal pollute the air of a big city?", "3", "Copper", "Chromium", "Lead","Cadmium",cat);
    questiondao.addQuestion(q0);
    q0 = new Question(1,"Bell metal is an alloy of", "4", "nickel and copper", "zinc and copper", "brass and nickel","tin and copper",cat);
    questiondao.addQuestion(q0);
    q0 = new Question(1,"Water is a good solvent of ionic salts because", "3", "it has a high specific heat", "it has no colour", "it has a high dipole moment","it has a high boiling point",cat);
    questiondao.addQuestion(q0);
    q0 = new Question(1,"Which of the following is not an isotope of hydrogen?", "4", "Tritium", "Deuterium", "Protium","Yttrium",cat);
    questiondao.addQuestion(q0);
    q0 = new Question(1,"The main constituents of pearls are", "2", "calcium oxide and ammonium chloride", "calcium carbonate and magnesium carbonate", "aragonite and conchiolin","ammonium sulphate and sodium carbonate",cat);
    questiondao.addQuestion(q0);
    q0 = new Question(1,"Amalgams are", "2", "highly coloured alloys", "alloys which contain mercury as one of the contents", "alloys which have great resistance to abrasion","alloys which contain carbon",cat);
    questiondao.addQuestion(q0);
    q0 = new Question(1,"Which of the following is the lightest metal?", "2", "Mercury", "Lithium", "Lead","Silver",cat);
    questiondao.addQuestion(q0);
    q0 = new Question(1,"Which of the following is an element?", "4", "Ruby", "Sapphire", "Emerald","Diamond",cat);
    questiondao.addQuestion(q0);



    cat ="General";
    q0 = new Question(1,"Grand Central Terminal, Park Avenue, New York is the world's", "1", "largest railway station", "highest railway station", "longest railway station","None of the above",cat);
    questiondao.addQuestion(q0);
    q0 = new Question(1,"Entomology is the science that studies", "2", "Behavior of human beings", "Insects", "The origin and history of technical and scientific terms","The formation of rocks",cat);
    questiondao.addQuestion(q0);
    q0 = new Question(1,"Eritrea, which became the 182nd member of the UN in 1993, is in the continent of", "4", "Asia", "Europe", "Australia","Africa",cat);
    questiondao.addQuestion(q0);
    q0 = new Question(1,"Garampani sanctuary is located at", "2", "Junagarh, Gujarat", "Diphu, Assam", "Kohima, Nagaland","Gangtok, Sikkim",cat);
    questiondao.addQuestion(q0);
    q0 = new Question(1,"For which of the following disciplines is Nobel Prize awarded?", "4", "Physics and Chemistry", "Physiology or Medicine", "Literature, Peace and Economics","All of the above",cat);
    questiondao.addQuestion(q0);
    q0 = new Question(1,"Hitler party which came into power in 1933 is known as", "2", "Labour Party", "Nazi Party", "Ku-Klux-Klan","Democratic Party",cat);
    questiondao.addQuestion(q0);
    q0 = new Question(1,"FFC stands for", "2", "Foreign Finance Corporation", "Film Finance Corporation", "Federation of Football Council","None of the above",cat);
    questiondao.addQuestion(q0);
    q0 = new Question(1,"Fastest shorthand writer was", "1", "Dr. G. D. Bist", "J.R.D. Tata", "J.M. Tagore","Khudada Khan",cat);
    questiondao.addQuestion(q0);
    q0 = new Question(1,"Epsom (England) is the place associated with", "NNNN", "Horse racing", "Polo", "Shooting","Snooker",cat);
    questiondao.addQuestion(q0);
    q0 = new Question(1,"First human heart transplant operation conducted by Dr. Christiaan Barnard on Louis Washkansky, was conducted in", "NNNN", "1111", "222", "33333","44444",cat);
    questiondao.addQuestion(q0);
    q0 = new Question(1,"QQQQQQQ", "NNNN", "1111", "222", "33333","44444",cat);
    questiondao.addQuestion(q0);
    q0 = new Question(1,"QQQQQQQ", "NNNN", "1111", "222", "33333","44444",cat);
    questiondao.addQuestion(q0);
    q0 = new Question(1,"QQQQQQQ", "NNNN", "1111", "222", "33333","44444",cat);
    questiondao.addQuestion(q0);
    q0 = new Question(1,"QQQQQQQ", "NNNN", "1111", "222", "33333","44444",cat);
    questiondao.addQuestion(q0);
    q0 = new Question(1,"QQQQQQQ", "NNNN", "1111", "222", "33333","44444",cat);
    questiondao.addQuestion(q0);
    q0 = new Question(1,"QQQQQQQ", "NNNN", "1111", "222", "33333","44444",cat);
    questiondao.addQuestion(q0);
    q0 = new Question(1,"QQQQQQQ", "NNNN", "1111", "222", "33333","44444",cat);
    questiondao.addQuestion(q0);
    q0 = new Question(1,"QQQQQQQ", "NNNN", "1111", "222", "33333","44444",cat);
    questiondao.addQuestion(q0);
    q0 = new Question(1,"QQQQQQQ", "NNNN", "1111", "222", "33333","44444",cat);
    questiondao.addQuestion(q0);
    q0 = new Question(1,"QQQQQQQ", "NNNN", "1111", "222", "33333","44444",cat);
    questiondao.addQuestion(q0);
    q0 = new Question(1,"QQQQQQQ", "NNNN", "1111", "222", "33333","44444",cat);
    questiondao.addQuestion(q0);
    q0 = new Question(1,"QQQQQQQ", "NNNN", "1111", "222", "33333","44444",cat);
    questiondao.addQuestion(q0);
    q0 = new Question(1,"QQQQQQQ", "NNNN", "1111", "222", "33333","44444",cat);
    questiondao.addQuestion(q0);
    q0 = new Question(1,"QQQQQQQ", "NNNN", "1111", "222", "33333","44444",cat);
    questiondao.addQuestion(q0);
    q0 = new Question(1,"QQQQQQQ", "NNNN", "1111", "222", "33333","44444",cat);
    questiondao.addQuestion(q0);
    q0 = new Question(1,"QQQQQQQ", "NNNN", "1111", "222", "33333","44444",cat);
    questiondao.addQuestion(q0);
    q0 = new Question(1,"QQQQQQQ", "NNNN", "1111", "222", "33333","44444",cat);
    questiondao.addQuestion(q0);
    q0 = new Question(1,"QQQQQQQ", "NNNN", "1111", "222", "33333","44444",cat);
    questiondao.addQuestion(q0);
    q0 = new Question(1,"QQQQQQQ", "NNNN", "1111", "222", "33333","44444",cat);
    questiondao.addQuestion(q0);
    q0 = new Question(1,"QQQQQQQ", "NNNN", "1111", "222", "33333","44444",cat);
    questiondao.addQuestion(q0);
    q0 = new Question(1,"QQQQQQQ", "NNNN", "1111", "222", "33333","44444",cat);
    questiondao.addQuestion(q0);
    q0 = new Question(1,"QQQQQQQ", "NNNN", "1111", "222", "33333","44444",cat);
    questiondao.addQuestion(q0);
    q0 = new Question(1,"QQQQQQQ", "NNNN", "1111", "222", "33333","44444",cat);
    questiondao.addQuestion(q0);
    q0 = new Question(1,"QQQQQQQ", "NNNN", "1111", "222", "33333","44444",cat);
    questiondao.addQuestion(q0);
    q0 = new Question(1,"QQQQQQQ", "NNNN", "1111", "222", "33333","44444",cat);
    questiondao.addQuestion(q0);
    q0 = new Question(1,"QQQQQQQ", "NNNN", "1111", "222", "33333","44444",cat);
    questiondao.addQuestion(q0);
    q0 = new Question(1,"QQQQQQQ", "NNNN", "1111", "222", "33333","44444",cat);
    questiondao.addQuestion(q0);
    q0 = new Question(1,"QQQQQQQ", "NNNN", "1111", "222", "33333","44444",cat);
    questiondao.addQuestion(q0);


// END



}


}
